name: kirin
version: 2.1.4
description: Minecraft server starter in Discord
license: GPL-3.0
author: FalloutStudios
files:
  - 'kirin.mjs'
  - 'Kirin'
supportedRecipleVersions:
  - ^7.0.9
dependencies:
  minecraft-protocol: ^1.40.3
