name: kirin
version: 2.1.4
description: Minecraft server starter in Discord
license: GPL-3.0
author: FalloutStudios
files:
  - 'Kirin'
  - '_kirin.createConfig.js'
  - 'kirin.js'
supportedRecipleVersions:
  - ^5.1.0
  - ^6.0.0
dependencies:
  minecraft-protocol: ^1.36.1
